package errno

const (
	SUCCESS = 0

	E_SYS_INVALID_DCONF = 11
	E_SYS_INIT_LOG_FAIL = 12

	E_COMMON_FILE_NOT_EXIST    = 101
	E_COMMON_READ_FILE_ERROR   = 102
	E_COMMON_JSON_ENCODE_ERROR = 103
	E_COMMON_JSON_DECODE_ERROR = 104

	E_DBOX_INVALID_CMD = 1001
)
